version: '3.8'

services:
  database:
    image: 'postgres:13'
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 15433:80
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - ./pgadmin-data/:/var/lib/pgadmin/
