### ver información sobre todos los hábitos
GET http://localhost:3000/api/habits

### ver infomación sobre un hábito
GET http://localhost:3000/api/habits/3

### post para crear 
POST http://localhost:3000/api/habits
Content-Type: application/json

{
    "id": 1234,
    "name": "Alimentación saludable",
    "progress": 30.0
}

### delete para borrar
DELETE http://localhost:3000/api/habits/3

### patch para actualizar parcialmente un hábito
PATCH http://localhost:3000/api/habits/3