#-----------------------------------HÁBITOS------------------------------------------------------

### pantalla todos los hábitos que el usuario no tiene configurados
GET http://localhost:3000/api/habits
### Pantalla MIS hábitos
GET http://localhost:3000/api/habits/user/044a8e06-3aa6-4536-9d05-09143c58d7ca

### pantalla hábito
GET http://localhost:3000/api/habits/habit/3a19f4f4-e784-496b-8d02-e5da37546820/user/044a8e06-3aa6-4536-9d05-09143c58d7ca

### TODO: Quitar el usuario de la url y recoger el id de la session
PATCH http://localhost:3000/api/habits/habit/3a19f4f4-e784-496b-8d02-e5da37546820/user/044a8e06-3aa6-4536-9d05-09143c58d7ca/customize
Content-Type: application/json

{
  "custom_color": "FF8300"
}
### post para crear un hábito
POST http://localhost:3000/api/habits/habit/f7f27180-f817-44f3-8da3-312ae9be801e/user/044a8e06-3aa6-4536-9d05-09143c58d7ca
Content-Type: application/json

{
  "habit_user_type": "Desarrollo",
  "status": "EnProceso",
  "current_streak": 3,
  "best_streak": 3,
  "times_forged": 0,
  "times_forged_goal": 3,
  "settings": {
    "preferred_hour": "12:00",
    "custom_color": "de78e9",
    "commitment_level": "Superior",
    "intermediate_goal": 7
  }
}
### delete para borrar
DELETE http://localhost:3000/api/habits/habit/3a19f4f4-e784-496b-8d02-e5da37546820/user/044a8e06-3aa6-4536-9d05-09143c58d7ca

###
GET http://localhost:3000/api/habits/habit/3a19f4f4-e784-496b-8d02-e5da37546820/unit

###
GET http://localhost:3000/api/habits/habit/cc2699f5-a5e4-4d0b-a873-74a1088882ee/tips

#-----------------------------------CALENDARIO------------------------------------------------------

###
GET http://localhost:3000/api/calendar/all/user/044a8e06-3aa6-4536-9d05-09143c58d7ca?start_date=2024-02-25&end_date=2024-02-26
###
POST http://localhost:3000/api/calendar/2024-02-25/user/044a8e06-3aa6-4536-9d05-09143c58d7ca
Content-Type: application/json

{
  "habit_id": "3a19f4f4-e784-496b-8d02-e5da37546820",
  "user_id": "044a8e06-3aa6-4536-9d05-09143c58d7ca",
  "type": "Habito"
}
###
PATCH http://localhost:3000/api/calendar/2024-02-25/event/fa97ae16-cc8c-4946-89c2-24c4e4e6d071
Content-Type: application/json

{
  "done": true
}
###
DELETE http://localhost:3000/api/calendar/2024-02-25/id/fa97ae16-cc8c-4946-89c2-24c4e4e6d071

#-----------------------------------DIARIO------------------------------------------------------
###
GET http://localhost:3000/api/diary/2024-03-18

###
POST http://localhost:3000/api/diary/2024-03-18
Content-Type: application/json

{
  "user_id": "044a8e06-3aa6-4536-9d05-09143c58d7ca",
  "text": "Hola, soy Sergio Zapata y hoy es dia 18",
  "mood": "Bueno"
}

###
PATCH http://localhost:3000/api/diary/2024-03-19
Content-Type: application/json

{
  "mood": "Mal"
}
### 
DELETE http://localhost:3000/api/diary/user/044a8e06-3aa6-4536-9d05-09143c58d7ca/2024-03-19

#-----------------------------------INSTRUCCIONES------------------------------------------------------
###
GET http://localhost:3000/api/instructions/MisHabitos